language: python
python: 3.9
env:
  -TOX_ENV=py39
  -COVERALLS_REPO_TOKEN=2RLV91GwgsPZaGPITbm1SXCt0Fx4obOdu coveralls
install:
  - pip install tox
script:
  - docker run -d -p 6379:6379 redis
  - tox -e $TOX_ENV
